"""Add source fields to NewsTaks.

Revision ID: 45c2344915fc
Revises: 1fafd5dc3483
Create Date: 2025-11-23 13:16:42.717644

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45c2344915fc"
down_revision = "1fafd5dc3483"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_task",
        sa.Column(
            "rss_urls",
            sa.JSON(),
            nullable=False,
            server_default="{}",
        )
    )
    op.add_column(
        "news_task",
        sa.Column(
            "tg_urls",
            sa.JSON(),
            nullable=False,
            server_default="{}",
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_task", "tg_urls")
    op.drop_column("news_task", "rss_urls")
    # ### end Alembic commands ###
