"""Add fields to NewsTask.

Revision ID: 719be16570c5
Revises: a730d993a928
Create Date: 2025-10-31 21:13:10.400248

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "719be16570c5"
down_revision = "a730d993a928"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_task",
        sa.Column("non_relevant_news", sa.JSON(), server_default="[]", nullable=False),
    )
    op.add_column(
        "news_task",
        sa.Column("relevant_news", sa.JSON(), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_task", "relevant_news")
    op.drop_column("news_task", "non_relevant_news")
    # ### end Alembic commands ###
