"""Add rules field to Events model.

Revision ID: 09b6a2a64744
Revises: e4150d7cd9f5
Create Date: 2025-07-30 12:51:58.895269

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "09b6a2a64744"
down_revision = "e4150d7cd9f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("rules", sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "rules")
    # ### end Alembic commands ###
