"""Add TelegramUser table.

Revision ID: b8a9a864656f
Revises: bb422db1c07e
Create Date: 2025-06-07 16:31:11.533653

"""

# revision identifiers, used by Alembic.
revision = "b8a9a864656f"
down_revision = "bb422db1c07e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
