"""Add Settings table.

Revision ID: a730d993a928
Revises: 792364ffcd58
Create Date: 2025-10-22 19:56:28.198711

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a730d993a928"
down_revision = "792364ffcd58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("deepseek", sa.String(length=255), nullable=True),
        sa.Column("deepl", sa.String(length=255), nullable=True),
        sa.Column("rss_urls", sa.JSON(), nullable=False),
        sa.Column("tg_urls", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
