"""Add ticker to crypto task.

Revision ID: f039ab5c24bc
Revises: 64229d4858e5
Create Date: 2025-06-25 12:28:12.940029

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f039ab5c24bc"
down_revision = "64229d4858e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "crypto_task",
        sa.Column("ticker", sa.String(length=50), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("crypto_task", "ticker")
    # ### end Alembic commands ###
