"""empty message.

Revision ID: c41d9d3968c8
Revises: 5204ff91a031
Create Date: 2025-08-01 13:44:34.263650

"""



# revision identifiers, used by Alembic.
revision = "c41d9d3968c8"
down_revision = "5204ff91a031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
