"""Amend cryptotask table.

Revision ID: e41562f3fb41
Revises: 39d5513a13ee
Create Date: 2025-07-06 15:33:55.385939

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e41562f3fb41"
down_revision = "39d5513a13ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crypto_task", sa.Column("start_date", sa.DateTime(), nullable=True))
    op.add_column(
        "crypto_task",
        sa.Column("type", sa.String(length=10), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("crypto_task", "type")
    op.drop_column("crypto_task", "start_date")
    # ### end Alembic commands ###
