"""Add prompt model.

Revision ID: 48b08bdfca69
Revises: c41d9d3968c8
Create Date: 2025-09-14 10:27:14.514009

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48b08bdfca69"
down_revision = "c41d9d3968c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.Text(length=3000), nullable=False),
        sa.Column("crypto_role", sa.Text(length=3000), nullable=False),
        sa.Column("suggest_post", sa.Text(length=3000), nullable=False),
        sa.Column("post_examples", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prompt")
    # ### end Alembic commands ###
