"""Remove amount_ton field.

Revision ID: df08e3bd48e4
Revises: 09b6a2a64744
Create Date: 2025-07-30 13:32:36.176069

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df08e3bd48e4"
down_revision = "09b6a2a64744"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "amount_ton")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("amount_ton", sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
