"""Add relationship between tasks and telegram users.

Revision ID: 1fafd5dc3483
Revises: 719be16570c5
Create Date: 2025-11-21 18:14:53.141126

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1fafd5dc3483"
down_revision = "719be16570c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_user_news_task",
        sa.Column("tg_user_id", sa.Integer(), nullable=False),
        sa.Column("news_task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["news_task_id"],
            ["news_task.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["tg_user.id"],
        ),
        sa.PrimaryKeyConstraint("tg_user_id", "news_task_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tg_user_news_task")
    # ### end Alembic commands ###
