"""Add amended  measurement_time field from CryptoTask.

Revision ID: dabe3ec62764
Revises: b6991cff40f4
Create Date: 2025-07-12 18:21:52.088368

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dabe3ec62764"
down_revision = "b6991cff40f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("measurement_time", sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_task", schema=None) as batch_op:
        batch_op.drop_column("measurement_time")
    # ### end Alembic commands ###
