"""Add Event model.

Revision ID: e4150d7cd9f5
Revises: 71c5e6795aed
Create Date: 2025-07-30 12:49:56.916956

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e4150d7cd9f5"
down_revision = "71c5e6795aed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=5000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("results_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("translations", sa.JSON(), nullable=False),
        sa.Column("false_positives", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("positives", sa.JSON(), server_default="[]", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
