"""Add tg_chat_id field to user.

Revision ID: 9964173412dd
Revises: d4ff3ecbf993
Create Date: 2025-06-07 15:19:40.962023

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9964173412dd"
down_revision = "d4ff3ecbf993"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("tg_chat_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "tg_chat_id")
    # ### end Alembic commands ###
