"""Add processed field.

Revision ID: 792364ffcd58
Revises: a3a06af2c1f4
Create Date: 2025-10-19 18:05:38.692507

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "792364ffcd58"
down_revision = "a3a06af2c1f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news",
        sa.Column(
            "processed", sa.Boolean(),
            nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news", "processed")
    # ### end Alembic commands ###
