"""Remove tg_chat_id field to user.

Revision ID: bb422db1c07e
Revises: 9964173412dd
Create Date: 2025-06-07 15:36:54.387045

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb422db1c07e"
down_revision = "9964173412dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "tg_chat_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("tg_chat_id", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
