"""Add link field to NewsTask model.

Revision ID: 71c5e6795aed
Revises: dabe3ec62764
Create Date: 2025-07-29 12:45:54.702063

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "71c5e6795aed"
down_revision = "dabe3ec62764"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news_task", sa.Column("link", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_task", "link")
    # ### end Alembic commands ###
