"""Drop measurement_time field from CryptoTask.

Revision ID: b6991cff40f4
Revises: e41562f3fb41
Create Date: 2025-07-12 18:06:16.652843

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6991cff40f4"
down_revision = "e41562f3fb41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_task", schema=None) as batch_op:
        batch_op.drop_column("measurement_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "crypto_task",
        sa.Column("measurement_time", sa.DATETIME(), nullable=False),
    )

    # ### end Alembic commands ###
