"""Add is_active field to Event.

Revision ID: 5204ff91a031
Revises: df08e3bd48e4
Create Date: 2025-07-30 15:36:24.404685

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5204ff91a031"
down_revision = "df08e3bd48e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("is_active", sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "is_active")
    # ### end Alembic commands ###
