"""Add positives fields to NewsTask.

Revision ID: d4ff3ecbf993
Revises: 2b7380507a71
Create Date: 2025-05-21 11:36:57.456060

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4ff3ecbf993"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_task",
        sa.Column("false_positives", sa.JSON(), server_default="[]", nullable=False),
    )
    op.add_column(
        "news_task",
        sa.Column("positives", sa.JSON(), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_task", "positives")
    op.drop_column("news_task", "false_positives")
    # ### end Alembic commands ###
