"""Add source name to News.

Revision ID: 969473abd300
Revises: 45c2344915fc
Create Date: 2025-11-24 16:34:17.983301

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "969473abd300"
down_revision = "45c2344915fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news", sa.Column(
            "source_name",
            sa.String(length=100),
            nullable=False,
            server_default="unknown"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news", "source_name")
    # ### end Alembic commands ###
